version: '3.8'
services:
  db:
    image: postgres:13.10
    container_name: nam_asset_db
    ports:
      - "5934:5432"
    environment:
      - POSTGRES_DB=asset
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bujaka
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    external: true
    name: nam-asset-volume