springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  paths-to-match: /api/context/**,/api/contextService/**
spring:
  data:
    rest:
      base-path: /api
      defaultMediaType: application/json
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5934/asset
    username: postgres
    password: bujaka
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
      mode: never
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
    drop-first: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  devtools:
    add-properties: false
  kafka:
    bootstrap-servers: localhost:1515
